### ISSUE TITLE
Issues with "Running PK models with nlmixr" tutorial

### ISSUE THREAD

**Issue by JSC67** [nlmixrdevelopment/nlmixr#27]
Hi Matt,

As I think my nlmixr is properly running as far as I can tell (as I just posted in Issue #25), I think that there are two other issues with the "Running PK models with nlmixr" tutorial at https://cran.r-project.org/web/packages/nlmixr/vignettes/running_nlmixr.html which need addressing.  Following along with the first fit with the nlme algorithm, the numbers are different (between what I get and what's in the tutorial) but the differences are small, so that may be a bit irksome but isn't too disconcerting.  However, with the SAEM algorithm, the differences are substantial, as I reported a few weeks ago (but maybe the emphasis was lost with other things).  For example, in the tutorial the objective function value was 116.211 and the log likelihood was -58.1055, whereas I got OBJF = 349.6266 and log-likelihood = -174.8133 respectively.  I did set.seed() to two different values but seem to have gotten the same results both times.  Also, the plot should be unimodal for the theophylline data, but it's bimodal because somehow other data were included at a much later time.  (The theophylline data should only go up to about 25 hours, not 150.)  Here's the pasted output for the plot; there is a problem here somehow—DV shouldn't be lost:

> plot(fit.saem)
`geom_smooth()` using method = 'loess'
Warning messages:
1: Computation failed in `stat_smooth()`:
object 'DV' not found 
2: Computation failed in `stat_smooth()`:
object 'DV' not found 

[tutorial output.txt](https://github.com/nlmixrdevelopment/nlmixr/files/1669456/tutorial.output.txt)
[Rplot should be unimodal for fit.saem.pdf](https://github.com/nlmixrdevelopment/nlmixr/files/1669457/Rplot.should.be.unimodal.for.fit.saem.pdf)

**Comment by mattfidler** [comment]
There is a typo in the vignette.  

It currently reads:

```R
library(nlmixr)
uif <- function() {
    ini({
        tka <- .5
        tcl <- -3.2
        tv <- -1
        eta.ka ~ 1
        eta.cl ~ 2
        eta.v ~ 1
        add.err <- 0.1
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.err)
    })
}

fit <- nlmixr(uif, theo_md, est="saem")
```

For me this gives
```R
Compiling RxODE differential equations...done.
C:/Users/fidlema3/AppData/Local/nlmixr/rtools/mingw_64/bin/g++  -I"c:/Users/fidlema3/AppData/Local/nlmixr/R/include" -DNDEBUG       -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/nlmixr/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/STANHE~1/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/Rcpp/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/RCPPAR~1/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/RCPPEI~1/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/BH/include   -O2 -Wall  -mtune=generic -c saem374061b28f9x64.cpp -o saem374061b28f9x64.o
C:/Users/fidlema3/AppData/Local/nlmixr/rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem374061b28f9x64.dll tmp.def saem374061b28f9x64.o C:/Users/fidlema3/AppData/Local/Temp/ep/RtmpUlWThp/rx_c19ccb8fc457a41226c9994187618af7_x64.dll -Lc:/Users/fidlema3/AppData/Local/nlmixr/R/bin/x64 -lRblas -Lc:/Users/fidlema3/AppData/Local/nlmixr/R/bin/x64 -lRlapack -lgfortran -lm -lquadmath -Lc:/Users/fidlema3/AppData/Local/nlmixr/R/bin/x64 -lR
done.
1:    0.0022  -2.9098  -0.6295   0.9500   1.9000   0.9500   9.0092
...
Calculating Table Variables...
done
> fit
nlmixr SAEM fit (ODE)

     OBJF      AIC      BIC Log-likelihood
 349.6266 363.6266 388.6583      -174.8133

Time (sec; $time):
          saem setup Likelihood Calculation covariance table
elapsed 134.39  0.67                   0.14          0  2.25

Parameters ($par.fixed):
        Estimate     SE    CV Untransformed          (95%CI)
tka        0.281  0.137 48.6%          1.32     (1.01, 1.73)
tcl        -3.19 0.0653  2.0%        0.0413 (0.0363, 0.0469)
tv        -0.811 0.0399  4.9%         0.445   (0.411, 0.481)
add.err     1.02                       1.02                 

Omega ($omega):
          eta.ka     eta.cl      eta.v
eta.ka 0.2046738 0.00000000 0.00000000
eta.cl 0.0000000 0.04781312 0.00000000
eta.v  0.0000000 0.00000000 0.01500266

Fit Data (object is a modified data.frame):
# A tibble: 264 x 15
  ID     TIME    DV         IPRED          PRED   IRES   RES  IWRES  WRES CWRES
  <fct> <dbl> <dbl>         <dbl>         <dbl>  <dbl> <dbl>  <dbl> <dbl> <dbl>
1 1     0     0.740  Inf.NaNe-315  Inf.NaNe-315  0.740 0.740  0.727 0.727 0.727
2 1     0.250 2.84      3.51e+  0     2.52e+  0 -0.675 0.323 -0.663 0.225 0.287
3 1     0.570 6.57      6.33e+  0     4.65e+  0  0.237 1.92   0.233 1.05  0.990
# ... with 261 more rows, and 5 more variables: CPRED <dbl>, CRES <dbl>, eta.ka
#   <dbl>, eta.cl <dbl>, eta.v <dbl>
> 
```

However, the `theo_md`  (the multiple dose theophilline example) was actually run with the `theo_sd` example as follows:

```
> uif <- function() {
    ini({
        tka <- .5
        tcl <- -3.2
        tv <- -1
        eta.ka ~ 1
        eta.cl ~ 2
        eta.v ~ 1
        add.err <- 0.1
    })
    model({
        ka <- exp(tka + eta.ka)
        cl <- exp(tcl + eta.cl)
        v <- exp(tv + eta.v)
        d/dt(depot) = -ka * depot
        d/dt(center) = ka * depot - cl / v * center
        cp = center / v
        cp ~ add(add.err)
    })
}
uif <- function() {
+     ini({
+         tka <- .5
+         tcl <- -3.2
+         tv <- -1
+         eta.ka ~ 1
+         eta.cl ~ 2
+         eta.v ~ 1
+         add.err <- 0.1
+     })
+     model({
+         ka <- exp(tka + eta.ka)
+         cl <- exp(tcl + eta.cl)
+         v <- exp(tv + eta.v)
+         d/dt(depot) = -ka * depot
+         d/dt(center) = ka * depot - cl / v * center
+         cp = center / v
+         cp ~ add(add.err)
+     })
+ }
> fit <- nlmixr(uif, theo_sd, est="saem")
Compiling RxODE differential equations...done.
C:/Users/fidlema3/AppData/Local/nlmixr/rtools/mingw_64/bin/g++  -I"c:/Users/fidlema3/AppData/Local/nlmixr/R/include" -DNDEBUG       -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/nlmixr/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/STANHE~1/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/Rcpp/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/RCPPAR~1/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/RCPPEI~1/include -Ic:/Users/fidlema3/AppData/Local/nlmixr/R/library/BH/include   -O2 -Wall  -mtune=generic -c saem37406f42aa1x64.cpp -o saem37406f42aa1x64.o
C:/Users/fidlema3/AppData/Local/nlmixr/rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o saem37406f42aa1x64.dll tmp.def saem37406f42aa1x64.o C:/Users/fidlema3/AppData/Local/Temp/ep/RtmpUlWThp/rx_c19ccb8fc457a41226c9994187618af7_x64.dll -Lc:/Users/fidlema3/AppData/Local/nlmixr/R/bin/x64 -lRblas -Lc:/Users/fidlema3/AppData/Local/nlmixr/R/bin/x64 -lRlapack -lgfortran -lm -lquadmath -Lc:/Users/fidlema3/AppData/Local/nlmixr/R/bin/x64 -lR
done.
1:    0.1503  -3.3314  -0.6447   0.9500   1.9000   0.9500   9.6167
2:    0.5210  -3.5986  -0.5154   0.9025   1.8050   0.9025   4.2880
3:    0.7840  -3.5040  -0.6070   0.8574   1.7147   0.8574   2.1259
....
> fit
nlmixr SAEM fit (ODE)

     OBJF      AIC      BIC Log-likelihood
 116.1369 130.1369 150.3165      -58.06845

Time (sec; $time):
         saem setup Likelihood Calculation covariance table
elapsed 38.44 21.89                   0.59          0  1.78

Parameters ($par.fixed):
        Estimate     SE    CV Untransformed          (95%CI)
tka        0.455  0.197 43.3%          1.58     (1.07, 2.32)
tcl        -3.22 0.0802  2.5%        0.0401 (0.0343, 0.0469)
tv        -0.784 0.0431  5.5%         0.457   (0.420, 0.497)
add.err    0.691                      0.691                 

Omega ($omega):
          eta.ka     eta.cl      eta.v
eta.ka 0.4367946 0.00000000 0.00000000
eta.cl 0.0000000 0.06929573 0.00000000
eta.v  0.0000000 0.00000000 0.01842363

Fit Data (object is a modified data.frame):
# A tibble: 132 x 15
  ID     TIME    DV          IPRED           PRED   IRES     RES  IWRES    WRES
  <fct> <dbl> <dbl>          <dbl>          <dbl>  <dbl>   <dbl>  <dbl>   <dbl>
1 1     0     0.740   Inf.NaNe-315   Inf.NaNe-315  0.740 0.740    1.07  1.07   
2 1     0.250 2.84       3.87e+  0      2.83e+  0 -1.03  0.00529 -1.50  0.00308
3 1     0.570 6.57       6.80e+  0      5.07e+  0 -0.230 1.50    -0.332 0.659  
# ... with 129 more rows, and 6 more variables: CWRES <dbl>, CPRED <dbl>, CRES
#   <dbl>, eta.ka <dbl>, eta.cl <dbl>, eta.v <dbl>
> 
```

These are not generated from R like typical markdown documents.  Rather because of CRAN limitations on time to run, these have to be manually entered.  

Please accept my apology for the typo.  It can be quite frustrating.

**Comment by mattfidler** [comment]
Note the `DV` is actually not dropped from the nlmixr data frame, though for some reason plotting it gives the warning you see above.

**Comment by mattfidler** [comment]
My guess the `DV` is missing because of `ggplot`s non-standard evaluation.  I fixed the vignette so the results make more sense.  However, it really does not affect the plot.

**Comment by mattfidler** [comment]
Also, as a note, for SAEM the seed is set to `99` by default.  You can change this with `saemControl`.  The `set.seed` doesn't really have any effect for the `nlmixr` fit.

For more information you can get help by `?saemControl`

**Comment by JSC67** [comment]
Thank-you for pointing out the insidious typo.  However, the URL https://cran.r-project.org/web/packages/nlmixr/vignettes/running_nlmixr.html still shows fit <- nlmixr(uif, theo_md, est="saem") but shows instead the results for fit <- nlmixr(uif, theo_sd, est="saem").

**Comment by mattfidler** [comment]
That is quite true.  We have to resubmit to  cran to fix this.  We are
working toward the next CRAN release.
